services:
  app:
    image: ghcr.io/nanyak/url_shortener_api:latest
    ports:
      - "9808:9808"
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      ai:
        condition: service_started
    env_file:
      - .env
    environment:
      - AI_SERVICE_URL=http://ai:8000

  ai:
    image: ghcr.io/nanyak/stuffsy_ai:latest
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
    environment:
      - REDIS_URL=redis://redis:6379

  worker:
    image: ghcr.io/nanyak/stuffsy_worker:latest
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongodb_data:
