services:
  app:
    image: ghcr.io/nanyak/url_shortener_api:latest
    ports:
      - "9808:9808"
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongodb_data:
