name: Deploy to VPS
on:
  workflow_run:
    workflows: ["Build and push"]
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull images
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker pull ghcr.io/nanyak/url_shortener_api:${{ github.event.workflow_run.head_sha }}
            docker pull ghcr.io/nanyak/stuffsy_ai:${{ github.event.workflow_run.head_sha }}
            docker pull ghcr.io/nanyak/stuffsy_worker:${{ github.event.workflow_run.head_sha }}
            docker tag ghcr.io/nanyak/url_shortener_api:${{ github.event.workflow_run.head_sha }} ghcr.io/nanyak/url_shortener_api:latest
            docker tag ghcr.io/nanyak/stuffsy_ai:${{ github.event.workflow_run.head_sha }} ghcr.io/nanyak/stuffsy_ai:latest
            docker tag ghcr.io/nanyak/stuffsy_worker:${{ github.event.workflow_run.head_sha }} ghcr.io/nanyak/stuffsy_worker:latest
            docker compose -f /home/thangdq/api/docker-compose.yml up -d
